import { Project, ProjectKPIs, AuditTelemetryEvent } from "@/types/project";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "JAX-2026-089",
    title: "Impact of Micro-credentials on Tech Sector Employability in Metro Manila",
    client: "Dr. Aris Thorne",
    university: "De La Salle University",
    field: "Economics & Labor Studies",
    statisticians: "Dr. Santos",
    method: "Hierarchical Linear Modeling (HLM) with Propensity Score Matching",
    status: "UNDER_EVALUATION",
    qaStatus: "IN_QA_REVIEW",
    paymentStatus: "DOWNPAYMENT_PAID",
    updated: "22m ago",
    datasetName: "tech_credentials_survey_n4500.csv",
    datasetSize: "2.4 MB",
    syntaxName: "hlm_propensity_matching.sps",
    artifacts: [
      { name: "tech_credentials_survey_n4500.csv", size: "2.4 MB", mimeType: "text/csv", verified: true, uploadedAt: "2h ago" },
      { name: "hlm_propensity_matching.sps", size: "18 KB", mimeType: "application/x-spss-syntax", verified: true, uploadedAt: "1h ago" },
    ],
  },
  {
    id: "JAX-2026-088",
    title: "Efficacy of Blended Problem-Based Learning on Clinical Diagnostic Speed",
    client: "Maria Clara Santos",
    university: "UST Medicine",
    field: "Health Sciences / Clinical Education",
    statisticians: "Prof. Rivera",
    method: "Two-Way Repeated Measures ANOVA & Bonferroni Post-Hoc",
    status: "ANALYSIS_IN_PROGRESS",
    qaStatus: "QA_APPROVED",
    paymentStatus: "FULLY_PAID",
    updated: "1h ago",
    datasetName: "clinical_trial_speed_t1_t2.xlsx",
    datasetSize: "1.1 MB",
    syntaxName: "twoway_repeated_anova.sps",
    artifacts: [
      { name: "clinical_trial_speed_t1_t2.xlsx", size: "1.1 MB", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", verified: true, uploadedAt: "4h ago" },
      { name: "twoway_repeated_anova.sps", size: "14 KB", mimeType: "application/x-spss-syntax", verified: true, uploadedAt: "2h ago" },
    ],
  },
  {
    id: "JAX-2026-087",
    title: "Mediating Role of Organizational Trust on Burnout during Agile Transitions",
    client: "Engr. Jonathan Reyes",
    university: "Mapúa University",
    field: "Industrial Engineering & Ergonomics",
    statisticians: "Dr. Alcantara",
    method: "Structural Equation Modeling (PLS-SEM with SmartPLS 4 & R)",
    status: "IN_REVIEW",
    qaStatus: "FOR_QA",
    paymentStatus: "DOWNPAYMENT_PAID",
    updated: "3h ago",
    datasetName: "agile_burnout_likert_n820.sav",
    datasetSize: "840 KB",
    syntaxName: "pls_sem_mediation_model.R",
    artifacts: [
      { name: "agile_burnout_likert_n820.sav", size: "840 KB", mimeType: "application/x-spss-sav", verified: true, uploadedAt: "6h ago" },
      { name: "pls_sem_mediation_model.R", size: "22 KB", mimeType: "text/x-r", verified: true, uploadedAt: "3h ago" },
    ],
  },
  {
    id: "JAX-2026-086",
    title: "Cross-Sectional Determinants of ESG Compliance among Philippine SMEs",
    client: "Prof. Elena Bautista",
    university: "UP Diliman",
    field: "Business Administration & Sustainability",
    statisticians: "Dr. Santos",
    method: "Multinomial Logistic Regression with Robust Standard Errors",
    status: "APPROVED",
    qaStatus: "QA_APPROVED",
    paymentStatus: "FULLY_PAID",
    updated: "5h ago",
    datasetName: "sme_esg_metrics_2025.csv",
    datasetSize: "3.2 MB",
    syntaxName: "multinomial_logistic_regression.sps",
    artifacts: [
      { name: "sme_esg_metrics_2025.csv", size: "3.2 MB", mimeType: "text/csv", verified: true, uploadedAt: "8h ago" },
      { name: "multinomial_logistic_regression.sps", size: "16 KB", mimeType: "application/x-spss-syntax", verified: true, uploadedAt: "5h ago" },
    ],
  },
  {
    id: "JAX-2026-085",
    title: "Soil Microbiome Biodiversity Shift Under Biochar-Enriched Micro-Irrigation",
    client: "Kenneth Vance Diaz",
    university: "Central Luzon State University",
    field: "Agricultural Biotechnology",
    statisticians: "Prof. Rivera",
    method: "MANOVA & Principal Component Analysis (PCA)",
    status: "DRAFT",
    qaStatus: "FOR_QA",
    paymentStatus: "PENDING_VERIFICATION",
    updated: "1d ago",
    datasetName: "microbiome_otu_abundance.xlsx",
    datasetSize: "4.8 MB",
    syntaxName: "pca_biplot_generation.R",
    artifacts: [
      { name: "microbiome_otu_abundance.xlsx", size: "4.8 MB", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", verified: true, uploadedAt: "1d ago" },
    ],
  },
];

export const INITIAL_KPIS: ProjectKPIs = {
  totalActiveStudies: 142,
  totalActiveStudiesTrend: "+12% this month",
  underEvaluationCount: 18,
  qaReviewGateCount: 9,
  fullyPaidReleasedCount: 64,
  monthlyRevenueEscrow: "₱485,200",
  escrowSecuredRatio: "100% Escrow Secured",
};

export const INITIAL_AUDIT_STREAM: AuditTelemetryEvent[] = [
  {
    id: "aud-001",
    timestamp: "12m ago",
    actor: "Senior QA Lead (Prof. Rivera)",
    actorRole: "SENIOR_QA_LEAD",
    action: "approved p-value verification",
    targetId: "JAX-2026-088",
    detail: "Two-Way ANOVA · F(2, 58) = 14.82, p < .001, ηp² = .34",
    badgeText: "QA Verified",
    badgeType: "success",
  },
  {
    id: "aud-002",
    timestamp: "38m ago",
    actor: "Finance Officer",
    actorRole: "FINANCE_OFFICER",
    action: "verified downpayment proof receipt #84920 via GCash",
    targetId: "JAX-2026-089",
    detail: "Milestone 1 Escrow Locked · ₱4,500.00",
    badgeText: "Escrow Locked",
    badgeType: "info",
  },
  {
    id: "aud-003",
    timestamp: "1h ago",
    actor: "Lead Statistician (Dr. Santos)",
    actorRole: "STATISTICIAN",
    action: "generated APA 7th Chapter 4 tables",
    targetId: "JAX-2026-085",
    detail: "SPSS Syntax & Cleaned Dataset archived to Cloudflare R2",
    badgeText: "Artifacts Archived",
    badgeType: "info",
  },
  {
    id: "aud-004",
    timestamp: "2h ago",
    actor: "Client (Maria C.)",
    actorRole: "CLIENT",
    action: "submitted new thesis intake dataset (2,400 survey rows)",
    targetId: "JAX-2026-090",
    detail: "Trigger.dev automated hygiene worker scheduled",
    badgeText: "Worker Scheduled",
    badgeType: "info",
  },
];
